name: Build

on:
  push:      
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print config file
        run: |
          cat /.github//workflows/env-config.json

      - name: Read environment config
        id: config
        uses: actions/github-script@v5
        with:
          script: |
            const config = require('./env-config.json');
            const envConfig = config[${{ inputs.environment }}];
            core.setOutput('dotnetVersion', envConfig.dotnetVersion);
            core.setOutput('dockerImage', envConfig.dockerImage);
            core.setOutput('dockerRegistry', envConfig.dockerRegistry);
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
      # Not needed right now
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODE_COV_TOKEN }}
