name: Build

on:
  push:      
    branches: [mainly]
  pull_request:
    branches: [mainly]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: .github/workflows/env-config.json
      - name: Echo package.json
        run: echo "${{ steps.package.outputs.content }}"

      - name: Read environment config
        id: config
        uses: actions/github-script@v5
        with:
          script: |
            const config = require('./env-config.json');
            const envConfig = config[${{ steps.config.outputs.content }}];
            core.setOutput('dotnetVersion', envConfig.dotnetVersion);
            core.setOutput('dockerImage', envConfig.dockerImage);
            core.setOutput('dockerRegistry', envConfig.dockerRegistry);

      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ steps.config.outputs.dotnetVersion }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
      # Not needed right now
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODE_COV_TOKEN }}
