name: Generate and Share GUID via Gist

on: 
  push:
    branches:
      - main  

jobs:
  generate-and-share-guid:
    env:
        file_name: deployment-image-tag.txt
    runs-on: ubuntu-latest
    steps:
      - name: Generate GUID
        id: guid
        env:
            IMAGE_TAG: petstore-ref-arch-${{ github.sha }}
        run: echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Print GUID
        run: | 
            echo "GUID: ${{ steps.guid.outputs.image_tag }}"

      - name: Update Gist
        id: gist
        env:
          GIST_TOKEN: ${{ secrets.gist_token }}
          GIST_ID: ${{ secrets.gist_id }}
        run: |
            curl -X PATCH -H "Authorization: token $GIST_TOKEN" \
              -d '{"files": {"${{ env.file_name }}": {"content": "${{ steps.guid.outputs.image_tag }}"}}}' \
              "https://api.github.com/gists/$GIST_ID"
            echo "Gist updated: $GIST_ID"
            echo "Gist content: ${{ steps.guid.outputs.image_tag }}"
