name: Generate and Share GUID via Gist

on: 
  push:
    branches:
      - main  

jobs:
  generate-and-share-guid:
    env:
        file_name: deployment-image-tag.txt
    runs-on: ubuntu-latest
    steps:
      - name: Generate GUID
        id: guid
        env:
            IMAGE_TAG: petstore-ref-arch-${{ github.sha }}
        run: echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Print GUID
        run: | 
            echo "GUID: ${{ steps.guid.outputs.image_tag }}"

      - name: Create or Update Gist
        id: gist
        env:
          GIST_TOKEN: ${{ secrets.gist_token }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          if [ -z "$GIST_ID" ]; then
            # Create a new Gist
            RESPONSE=$(curl -X POST -H "Authorization: token $GIST_TOKEN" \
              -d '{"files": {"${{ env.file_name }}": {"content": "${{ steps.guid.outputs.image_tag }}"}}}' \
              "https://api.github.com/gists")
            NEW_GIST_ID=$(echo $RESPONSE | jq -r '.id')
            echo "New Gist created: $NEW_GIST_ID"
            echo "GIST_ID=$NEW_GIST_ID" >> $GITHUB_OUTPUT
          else
            # Update existing Gist
            curl -X PATCH -H "Authorization: token $GIST_TOKEN" \
              -d '{"files": {"${{ env.file_name }}": {"content": "${{ steps.guid.outputs.image_tag }}"}}}' \
              "https://api.github.com/gists/$GIST_ID"
            echo "Gist updated: $GIST_ID"
          fi
