name: Publish template to NuGet
on:
  workflow_dispatch:
  push:
    branches:
      - mainly

jobs:
  publish:
    name: Package & Publish template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        with:
          nuget-version: "5.x"

      - name: Package
        run: nuget pack Amantinband.CleanArchitecture.Template.nuspec -OutputDirectory artifacts -NoDefaultExcludes

      - name: Publish
        run: nuget push .\artifacts\*.nupkg -ApiKey ${{ secrets.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json -SkipDuplicate
