name: Use Reusable .NET Core CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/dotnet-ci-workflow.yml
    with:
      environment: 'development'
      